base_url = "https://sub0.productions/"
default_language = "en-us"
title = "sub0.productions"
theme = "papaya"

[extra]
cdn.font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
color_mode = "dark"
menu_items = []
