base_url = "https://sub0.productions/"
default_language = "en"
title = "sub0.productions"
description = "recorded and live sound engineering for a cappella"
compile_sass = true

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[extra]
menu_items = [
  { name = "about", url = "/about" },
  { name = "projects", url = "/projects" },
]
